name: next_audio_recorder
description: "A new audio recorder project."
version: 0.0.3
homepage: https://github.com/tranhuudang/next_audio_recoder

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  # This interface allows platform-specific implementations of the flutter_sound_record plugin,
  # as well as the plugin itself, to ensure they are supporting the same interface.
  flutter_sound_record_platform_interface: ^0.3.1
  audio_session: ^0.1.18
  path_provider: ^2.1.3